# Generated by Django 3.2.5 on 2021-10-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('publish_date', models.DateField()),
                ('section_1', models.CharField(default='', max_length=50)),
                ('sec_1_link_1', models.CharField(default='', max_length=100)),
                ('sec1_lnk1_name', models.CharField(default='', max_length=50)),
                ('sec_1_link_2', models.CharField(default='', max_length=100)),
                ('sec1_lnk2_name', models.CharField(default='', max_length=50)),
                ('sec_1_link_3', models.CharField(default='', max_length=100)),
                ('sec1_lnk3_name', models.CharField(default='', max_length=50)),
                ('sec_1_link_4', models.CharField(default='', max_length=100)),
                ('sec1_lnk4_name', models.CharField(default='', max_length=50)),
                ('section_2', models.CharField(default='', max_length=50)),
                ('sec_2_link_1', models.CharField(default='', max_length=100)),
                ('sec2_lnk1_name', models.CharField(default='', max_length=50)),
                ('sec_2_link_2', models.CharField(default='', max_length=100)),
                ('sec2_lnk2_name', models.CharField(default='', max_length=50)),
                ('sec_2_link_3', models.CharField(default='', max_length=100)),
                ('sec2_lnk3_name', models.CharField(default='', max_length=50)),
                ('sec_2_link_4', models.CharField(default='', max_length=100)),
                ('sec2_lnk4_name', models.CharField(default='', max_length=50)),
                ('section_3', models.CharField(default='', max_length=50)),
                ('sec_3_link_1', models.CharField(default='', max_length=100)),
                ('sec3_lnk1_name', models.CharField(default='', max_length=50)),
                ('sec_3_link_2', models.CharField(default='', max_length=100)),
                ('sec3_lnk2_name', models.CharField(default='', max_length=50)),
                ('sec_3_link_3', models.CharField(default='', max_length=100)),
                ('sec3_lnk3_name', models.CharField(default='', max_length=50)),
                ('sec_3_link_4', models.CharField(default='', max_length=100)),
                ('sec3_lnk4_name', models.CharField(default='', max_length=50)),
                ('section_4', models.CharField(default='', max_length=50)),
                ('sec_4_link_1', models.CharField(default='', max_length=100)),
                ('sec4_lnk1_name', models.CharField(default='', max_length=50)),
                ('sec_4_link_2', models.CharField(default='', max_length=100)),
                ('sec4_lnk2_name', models.CharField(default='', max_length=50)),
                ('sec_4_link_3', models.CharField(default='', max_length=100)),
                ('sec4_lnk3_name', models.CharField(default='', max_length=50)),
                ('sec_4_link_4', models.CharField(default='', max_length=100)),
                ('sec4_lnk4_name', models.CharField(default='', max_length=50)),
                ('section_5', models.CharField(default='', max_length=50)),
                ('sec_5_link_1', models.CharField(default='', max_length=100)),
                ('sec5_lnk1_name', models.CharField(default='', max_length=50)),
                ('sec_5_link_2', models.CharField(default='', max_length=100)),
                ('sec5_lnk2_name', models.CharField(default='', max_length=50)),
                ('sec_5_link_3', models.CharField(default='', max_length=100)),
                ('sec5_lnk3_name', models.CharField(default='', max_length=50)),
                ('sec_5_link_4', models.CharField(default='', max_length=100)),
                ('sec5_lnk4_name', models.CharField(default='', max_length=50)),
                ('quiz', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Quizze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('link', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
