# Generated by Django 3.2.5 on 2021-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quiz',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizze',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quizze',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
